version: 2
registries:
  docker-registry-ezcater-jfrog-io:
    type: docker-registry
    url: https://ezcater-production.jfrog.io
    username: '${{secrets.ARTIFACTORY_USERNAME}}'
    password: '${{secrets.ARTIFACTORY_PASSWORD}}'
  npm-registry-ezcater-jfrog-io:
    type: npm-registry
    url: https://ezcater.jfrog.io/ezcater/api/npm/npm
    username: '${{secrets.ARTIFACTORY_USERNAME}}'
    password: '${{secrets.ARTIFACTORY_PASSWORD}}'
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '06:00'
    open-pull-requests-limit: 10
    registries:
      - npm-registry-ezcater-jfrog-io
    
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '06:00'
    open-pull-requests-limit: 10
    registries:
      - docker-registry-ezcater-jfrog-io
