name: Dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.tool-versions'
        cache: yarn

    - name: Install Dependencies
      shell: bash
      run: yarn install --immutable
